SELECT 
    USER_ID,
    NICKNAME,
    SUM(UGB.PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD UGB
JOIN
    USED_GOODS_USER UGS 
    ON UGB.WRITER_ID=UGS.USER_ID
WHERE STATUS LIKE 'DONE'
GROUP BY UGB.WRITER_ID HAVING SUM(UGB.PRICE)>=700000

ORDER BY SUM(UGB.PRICE)ASC
